# Generated by Django 3.2.1 on 2021-06-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPaperCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, unique=True)),
                ('count', models.IntegerField()),
                ('conference', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'author-ranking',
                'verbose_name_plural': 'author-ranking',
                'ordering': ['id'],
            },
        ),
    ]
