# Generated by Django 3.2.1 on 2021-06-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0005_alter_paper_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('collection_time', models.DateField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.paper')),
            ],
            options={
                'verbose_name': 'user-collection',
                'verbose_name_plural': 'user-collection',
                'ordering': ['user_id', 'collection_time'],
            },
        ),
    ]
